### ISSUE TITLE
Bug: Wrapper and computed properties are not testable using Typescript

### ISSUE THREAD

**Issue by telion2** [vuejs/test-utils#1368]
**Describe the bug**

Basically, I get Type Error when writing test following https://lmiller1990.github.io/vue-testing-handbook/v3/computed-properties.html#testing-computed-properties

I have a simple component: 

```ts
computed: {
    _test(): string {
      return "test";
    },
  },
  methods: {
    test() :string {
      return "test";
    },
  },
```

But when trying to test them I run into the following Issues: 
```ts
import App from "@/App.ce.vue";    //.ce. doesn't make a difference. Tried without it too
let appWrapper: VueWrapper;
beforeEach(() => {
    appWrapper = shallowMount(App, {  });
  });
test("test", () => {
        /*
         Property 'test' does not exist on type 'ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, 
         any, any, any, any, any, any, any, {}>>'.ts(2339)
        */
        console.log(appWrapper.vm.test());
        /*
           Property '_test' does not exist on type 'ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any,  
           any, any, any, any, any, any, any, any, {}>>'.ts(2339)
        */
         console.log(appWrapper.vm._test);
        /*
            Property 'call' does not exist on type 'ComputedGetter<any> | WritableComputedOptions<any>'.
            Property 'call' does not exist on type 'WritableComputedOptions<any>'.ts(2339)
        */
        console.log(App.computed?._test.call());
});
```
However if I I log  `appWrapper.vm` then the properties are available as expected. However, TS prevents the test from starting since it thinks its an Error.

The Vue Project was simply created using the almost latest vue cli. 

**Expected behavior**
That vue test utils is either inherently compatible with TS or the documentations shows how to get around those TS Errors. 
It should be possible to write a test of a computed property using TS using either the .call or the wrapper variation. 

**Related information:**
- `@vue/test-utils` version: ^2.0.0-0
- "vue": "^3.2.13",
- `Vue` version: @vue/cli 4.5.15
- `node` version: v14.10.1
- `npm` (or `yarn`) version: 8.4.0

**Comment by freakzlike** [comment]
```ts
let appWrapper: VueWrapper;
```
With this line you explicit define your `appWrapper` to be type of `VueWrapper` without any specific component. Try to allow `shallowMount` to provide to correct type for your:

```ts
test("test", () => {
  const appWrapper = shallowMount(App);
  console.log(appWrapper.vm.test());
  console.log(appWrapper.vm._test);
  console.log(App.computed?._test.call(this));

  // TypeError because it does not exist
  console.log(appWrapper.vm.other());
});

```

**Comment by telion2** [comment]
Thank you. That solves the Wrapper Issue. 

However: `console.log(App.computed?._test.call(this));` is run on the imported component directly. 
Meaning: 
```ts
import App from "App.vue"
test("sometest",=>{
     console.log(App.computed?._test.call(this));
})
```
will result in: 
```
Property 'call' does not exist on type 'ComputedGetter<any> | WritableComputedOptions<any>'.
Property 'call' does not exist on type 'WritableComputedOptions<any>'.ts(2339)
```

Following the guide here: https://lmiller1990.github.io/vue-testing-handbook/computed-properties.html

**Comment by cexbrayat** [comment]
@telion2 Yeah, I'm not sure this is the proper way to test computed properties (cc @lmiller1990 ). 

Usually, you are going to use this computed property in the template, and a unit test can just mount the component, and check that the template displays the proper text for example. Or you can check the `wrapper.vm` as you did

I'm going to close the issue as this is not a problem with VTU: @freakzlike pointed the right direction to handle the original problem by letting TypeScript infer the proper type of the wrapper 👍

**Comment by cexbrayat** [comment]
I understand your point, and agree with you; That's why I would argue just testing a computed property is not really worth it, and you're more likely to test what the component really does in real life (how it uses it to display something to your users).

Furthermore, your example is using the Options API, which is supported, but a lot of Vue 3 developers are using the Composition API. In that case, `App.computed?._test.call(this)` is not evenly possible, as there is no `computed` property on your component. So I think you can safely forget about that way of testing computed props 😉

**Comment by telion2** [comment]
"...just testing a computed property is not really worth it, and you're more likely to test what the component really does in real life (how it uses it to display something to your users)."
Isn't that the difference between "e2e" (or integration / UI test) and unit-tests? 
Because displaying something is a html/vue feature that don't need to test from a unit-test perspective. 
In other words, these things are vue features I don't need to test:  
```
v-if="value"
v-for="value in values"
{{  value }}
v-bind="options"
@event="handler"
etc.
```
I just need to make sure the correct values are generated, that control the UI. 

If I want to e2e test my application, I would test the compiled UI anyways, because testing UI before building introduces risks that happen during building. 

And I don't know of course what kind of computed properties people write, but I do complex ones. E.g.: 
Imagine an autocomplete with a set of entities. 
These should be filtered by some preconditions. 

Now I would do that with a computed property: (I just thought this one out on the fly)
```ts
displayedEntities(){
      let entities: Array =  this.$store.getters.getAllEntities(); 
      entities = entities.filter((el:Entity) =>el.type === this.selectedType);
      if(entities.length === 0) this.disableAutocomplete = true;
      return entities;
},
displayedLabel(){
    return this.$t(this.label);
}
```
If you deal with displayedLabel I would understand you. Testing that is not worth it. 
But displayedEntities needs testing. 

Yeah, I know about the composition API, but I have impatient clients, running projects and a team that also needs to understand the code. I'm already happy that we go for Vue 3 now, but changing everything at once takes too much time while coding. 
I would also argue that the majority of Vue devs are coming from Vue 2 and therefore used to the Options API and probably in a similar situation like me. 

Testing a composition API style component, will be something new for me, which will need time, to check out, but I am the kind of guy that will do it at some point, but now would be to early.

**Comment by lmiller1990** [comment]
I've encountered the problem you've described many times. I even showed a simple example in the link, as as @cexbrayat, it's probably not ideal in many scenarios. I should definitely review some parts of that book I wrote - I basically wrote it as I learned to code, before I really started to be more critical about my testing approach. 

To take your example:

```js
displayedEntities(){
  let entities: Array =  this.$store.getters.getAllEntities(); 
  entities = entities.filter((el:Entity) =>el.type === this.selectedType);
  if(entities.length === 0) this.disableAutocomplete = true;
  return entities;
}
```

To truly test this in isolation, exercising every code path, you need two test (one where entities is empty, one where it isn't). You could do:

```js
test('it works', () => {
 let localThis = { 
    disableAutocomplete: false,
    $store: {
      getters: {
        getAllEntities: () => []
      }
    }
  }

  displayedEntities,call(localThis)
  
  expect(localThis.disableAutocomplete).toBe(true)
})
```

While this does work, the problem I've encountered with this style of test is if you remove Vuex from your app, for example. your tests still pass. Back when I was really into modular unit testing, I'd argue "the unit still works. I have other unit tests for Vuex, those will fail". Although this is true, my experience has shown me that this can lead to false confidence; a lot of your tests may pass, when really the entire app is completely broken.

It's for this reason I don't often unit test things in `methods` or `computed`. If the logic was truly complex, I'd probably unit test it, but in a different fashion. I'd also recommend some refactoring here. Also considering you said "In other words, these things are Vue features I don't need to test", we probably want to extract *all* the logic into pure, stateless methods. 

I've found this technique useful when I was working on a Vue app where I had to parse a huge, complex JSON response then wrap it in a Vue application. I unit tested the parsing, and wrapped the result with `computed`.

Consider the goal of `displayedEntities`: filter the entities based a `type`. Since this is a computed property, it should not have any side effects, like setting `disabledAutocomplete` - this is derived based on the result of `displayedEntities`.

Recommended refactor:

```js
computed: {
  displayedEntities () {
    let entities: Array =  this.$store.getters.getAllEntities(); 
    entities = entities.filter((el) => el.type === this.selectedType);
    return entities;
  },

  disableAutocomplete () {
    return this.displayedEntities.length === 0
  }
},
```

Now if you want to unit test `displayedEntities`, you don't really want any global variables either, so we should pass `$store` as an arg.

```js
// decoupled from component
export function entitiesToDisplay (entities, selectedType) {
  return entities.filter((el) =>el.type === selectedType)
}

export default  {
  computed: {
    displayedEntities(){
      return entitiesToDisplay(this.$store.getters.getAllEntities(), this.selectedType)
    }
  }
}
```

Finally, now you can really unit test `entitiesToDisplay`, decoupled from Vue. You could also make a similar method for `disableAutocomplete` that takes `entities` as an arg.

There's a more complex example where I use this technique to test a complicated form: https://lachlan-miller.me/articles/writing-testable-forms
