### ISSUE TITLE
Bug: using global in mount() pollutes global object for other tests on mocha + vue/compat

### ISSUE THREAD

**Issue by hjri** [vuejs/test-utils#1382]
**Describe the bug**

When using `mount(Component, { global: {...}})` it appears that changes also affect other components/tests, i.e.
```js
describe('test', () => {
  it('ComponentA', () => {
    mount(ComponentA, { global: { mocks: { '$store': null }})
    // do some assertion
  })
  it('ComponentB', () => {
    const store = createStore(...)
    mount(ComponentB, { global: { plugins: [store] })
    // do some assertion
  })
})
```
This suite crashes when testing ComponentB because of `this.$store is null`, however if I skip the ComponentA test it will work fine.

**To Reproduce**

Write two tests/two components one of which uses mocked store to null and other uses real store.
Use mocha and vue/compat for testing.

**Expected behavior**

**Related information:**
- `@vue/test-utils` version: "2.0.0-rc.17"
- `Vue` version: "^3.1.0"
- `node` version: v14.19.1
- `npm` (or `yarn`) version: yarn v1.19.2

**Additional context**

using vue/compat with this config:
```js
import { configureCompat } from 'vue'
// disable compat for certain features
configureCompat({
  MODE: '3',
  COMPONENT_V_MODEL: false,
  INSTANCE_SET: false,
  RENDER_FUNCTION: false
})
```

**Comment by cexbrayat** [comment]
Hi @hjri 

Can you provide us a minimal repro so we can investigate please? You can use create-vue to generate a project and push the project to Github. Thanks!

**Comment by leopiccionia** [comment]
Legacy plugins modify the `Vue.prototype` singleton in compat mode. It's expected behavior, and was solved by `createLocalVue` in `@vue/test-utils` v1.

Vue 3 has a `createCompatVue` function, [worth investigating](https://github.com/vuejs/core/blob/v3.2.33/packages/runtime-core/src/compat/global.ts#L227-L244). It's exported inside `compatUtils`, but only on [compat builds](https://github.com/vuejs/core/blob/v3.2.33/packages/runtime-core/src/index.ts#L352-L365).

I don't know if a Vue 3 compat app could work in unpatched `@vue/test-utils` v1. I couldn't find recommendations for testing Vue 3 compat apps in documentation; has it already been figured out?

**Comment by cexbrayat** [comment]
We don't have a minimal repro to investigate, so I'll close for now. Feel free to reopen with a repro if this is still an issue!
