### ISSUE TITLE
Bug: Unable to findComponent/getComponent inside stubbed out teleport

### ISSUE THREAD

**Issue by marina-mosti** [vuejs/test-utils#1942]
With Vue 3.2.45 and latest VTU it is no longer possible to `findComponent` or `getComponent` inside a stubbed out Teleport _if_ they `v-if`d.

**Describe the bug**

**To Reproduce**

https://stackblitz.com/edit/vitest-dev-vitest-dmk68g?file=test/basic.test.ts

**Expected behavior**

Should be able to getComponent as before

**Related information:**

Outputs error:

```
Unable to get component with name X within: 
    <teleport-stub to="body">
      <!--v-if-->
    </teleport-stub>
```

**Additional context**

**Comment by marina-mosti** [comment]
It seems complicated to go back behind `3.2.19` due to the change in not needing the compiler-sfc anymore, at least in stackblitz. Maybe the problem is in the way that @vite/plugin-vue is parsing the files? I'll keep trying to find what's breaking it, but I feel like I'm pushing buttons and hoping it works

**Comment by lmiller1990** [comment]
Have you tried Jest? That would rule out a test runner specific bug.

**Comment by cexbrayat** [comment]
I looked into it, and I think this is because Vue treats Teleport slots a bit differently https://github.com/vuejs/core/blob/78b86150b801e7eb4ebf1cdff977e791dc0438f0/packages/runtime-core/src/vnode.ts#L770
So in our stub, we get a "non-reactive" slot that'll never update.

I can't think of a way to work around that in VTU, without hacking something that is already quite a bit hacky.
I think the simplest is probably to not use a stub in that case, even if I know this answer is not ideal.

**Comment by marina-mosti** [comment]
Hey @lmiller1990 sorry for the slow reply, yeah it doesnt work in jest either
@cexbrayat thanks for giving it a look, yeah thats def not ideal but its good to know ^^

**Comment by cexbrayat** [comment]
👍 Let's close it for now, as I don't think we can act on it. Maybe we should raise an issue on core to see if there's something we're missing, but I don't think it's too critical at this point: we can always revisit it later if needed.
