### ISSUE TITLE
Failed setting prop "attributes" on stub

### ISSUE THREAD

**Issue by ol1s** [vuejs/test-utils#1995]
Defining a prop named `attributes` on a stubbed component throws a warning.

```
Failed setting prop "attributes" on <child-component-stub>: value test123 is invalid:
```

https://stackblitz.com/edit/vitest-dev-vitest-wqbs9d?file=test/basic.test.ts

```js
import { defineComponent } from 'vue';
import { mount } from '@vue/test-utils';

const ChildComponent = defineComponent({
  props: {
    attributes: {
      type: String,
      default: null,
    },
  },
});

const ParentComponent = defineComponent({
  components: { ChildComponent },
  template: `<ChildComponent attributes="test123" />`,
});

test('it stubs component', () => {
  const wrapper = mount(ParentComponent, { shallow: true });
});
```

**Comment by cexbrayat** [comment]
Hi @ol1s 

Thank you for the repro

I think this expected (sort of), as `attributes` is a read-only DOM property (see https://developer.mozilla.org/en-US/docs/Web/API/Element/attributes), so Vue warns you about it.

You can reproduce with Vue itself easily: https://sfc.vuejs.org/#eNpNUE1rwzAM/SvCF6eQJuyadYWxy36EL2mrLC7xB5bcDYL/++Q0gx2M/CQ9vSet6j3G7pFRDepE12Qjn423LobEsMINJ+vxIwj26LmFGQpMKTjQwtGvxgPUhz8bQdrHvGzxP61Zaw8AIefYHGCHAEkSyYOk3s4wN/pmH7oV2ZE52UtmpAFeoLSgP3FZgj48iaWGIuDU75ZVq56ej26M3Z2Cl302GbMXyKjhT9goMV+xUTNzpKHvabrWK9ypC+mrl1+XsmfrsENyx0sK34RJBhu1aRtfVPkFFY5o/Q==

I don't think we can do much about that in VTU.

In your case, you can either:
- ignore the warning (spy on `console.warn for example)
- name your props differently
- use a custom stub instead of the automatically generated one
