### ISSUE TITLE
wrapper.emitted does not include custom events

### ISSUE THREAD

**Issue by lixiaofa** [vuejs/test-utils#2109]
**Describe the bug**
Custom event test error

**To Reproduce**
https://stackblitz.com/edit/github-8rjg3t?file=src%2Fcomponents%2Fsku%2Fsku.vue,src%2Fcomponents%2F__tests__%2Fsku.spec.ts,package.json,src%2Fcomponents%2FHelloWorld.vue
**Expected behavior**
no error

**Related information:**
"vitest": "^0.32.0",

**Additional context**

What should I do if I want to test the contents of .fs-sku-body__wrapper

**Comment by cexbrayat** [comment]
Hi @lixiaofa 

I don't think this is an issue in VTU because you never trigger the emission of the event, so `wrapper.emitted()` will not contain it.

You're trying to test the Popup component from Vant, which uses Teleport and Transition https://github.com/youzan/vant/blob/main/packages/vant/src/popup/Popup.tsx.

To test something that uses a real Transition take a look at this thread https://github.com/vuejs/test-utils/issues/1912#issuecomment-1351054542

I see that the Vant team is using VTU to test their components, so maybe take a look at the popup tests to see how they do it https://github.com/youzan/vant/tree/main/packages/vant/src/popup/test
Maybe try to test without the teleport option first to make sure you have a working test.

I hope this will help. If not, maybe try to ask a question on the Vant repository on how to properly write a Popup test, they'll know how to guide you more precisely (I don't use Vant, so I can only offer some general advice).

**Comment by lixiaofa** [comment]
> Hi @lixiaofa
> 
> I don't think this is an issue in VTU because you never trigger the emission of the event, so `wrapper.emitted()` will not contain it.
> 
> You're trying to test the Popup component from Vant, which uses Teleport and Transition https://github.com/youzan/vant/blob/main/packages/vant/src/popup/Popup.tsx.
> 
> To test something that uses a real Transition take a look at this thread [#1912 (comment)](https://github.com/vuejs/test-utils/issues/1912#issuecomment-1351054542)
> 
> I see that the Vant team is using VTU to test their components, so maybe take a look at the popup tests to see how they do it https://github.com/youzan/vant/tree/main/packages/vant/src/popup/test Maybe try to test without the teleport option first to make sure you have a working test.
> 
> I hope this will help. If not, maybe try to ask a question on the Vant repository on how to properly write a Popup test, they'll know how to guide you more precisely (I don't use Vant, so I can only offer some general advice).


hi @cexbrayat 
Actually I have three questions
1.  in case  ,  How to trigger the emission of the event. 
2. How should I test the add custom event here
3. Can't we do more with custom components like this

**Comment by cexbrayat** [comment]
1. If I understand correctly your example, the `add` custom event is triggered when you click on the button.
So your test needs to do something like `await wrapper.get('button').trigger('click')`

2. I don't understand what you mean by that

**Comment by lixiaofa** [comment]
> 1. If I understand correctly your example, the `add` custom event is triggered when you click on the button.
>    So your test needs to do something like `await wrapper.get('button').trigger('click')`
> 2. I don't understand what you mean by that

@cexbrayat 
in case  ， https://stackblitz.com/edit/github-8rjg3t?file=src%2Fcomponents%2Fsku%2Fsku.vue,src%2Fcomponents%2F__tests__%2Fsku.spec.ts,package.json,src%2Fcomponents%2FHelloWorld.vue
2.   If the custom component has this structure, what other tests can we do

**Comment by cexbrayat** [comment]
As I was mentioning, you should check out the tests from the Vant repository 

> I see that the Vant team is using VTU to test their components, so maybe take a look at the popup tests to see how they do it https://github.com/youzan/vant/tree/main/packages/vant/src/popup/test

**Comment by lixiaofa** [comment]
@cexbrayat 
I don't think testing the vant component is meaningful because it has already been tested
