### ISSUE TITLE
Feature request: Found differency in behavior on asserting custom events from vue-test-utils@1 and v2

### ISSUE THREAD

**Issue by daniilgri** [vuejs/test-utils#2153]
`<template>
    <button
      @click="handleClick"
    >
      <slot />
    </button>
`
The component has a button element that triggers a custom event called 'click' by clicking on it.
Doing it like this `await findByDataTestId(wrapper, MENU_LIST_ITEM_BUTTON_DATA_TEST_ID).trigger('click');`
 
In VTU1 to test if the custom event is actually triggered I could run something like that and check for the 'click' key existence.
`wrapper.emitted()`
But in VTU v2 `emitted()` object also contains a native event `{ click: [ [ [MouseEvent] ] ] }`. Why is this happening? I found a solution to use `.stop` modifier to stop bubbling.

**Comment by daniilgri** [comment]
Also according to your docs, it says that `emitted()` `Return an object containing custom events emitted by the Wrapper vm`

**Comment by daniilgri** [comment]
Also wanna hear your opinion on naming custom events with native events names, starting from vue3 it seems like a bad practice, what do you think?

**Comment by cexbrayat** [comment]
IIRC this is expected.

If you declare `click` in the `emits` of the component, then it should not show in the `emitted`. otherwise, it will, unless you stop it. See https://github.com/vuejs/test-utils/blob/0d924f97c1eb816b9159ceac19aeb575b0937a40/src/vueWrapper.ts#L172-L207

And I'm not a fan of having events with the same name as native events.
