### ISSUE TITLE
Bug: Vue Test Utils warns of missing render function for component that has render function

### ISSUE THREAD

**Issue by dospunk** [vuejs/test-utils#2182]
**Describe the bug**

When mounting a component that includes the "FlatPickr" component from vue-flatpickr-component, Vue prints a warning saying "Component is missing template or render function." The component works fine when running the Vue dev server and the component [does have a render function](https://github.com/ankurk91/vue-flatpickr-component/blob/main/src/component.ts#L18), which leads me to believe this is an issue in Vue Test Utils.

**To Reproduce**

https://stackblitz.com/edit/github-6m2gtt

run the `pnpm test:unit` command to see the warning.

**Expected behavior**

The FlatPickr component should be mounted correctly.

**Related information:**

System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 6.24 GB / 15.78 GB
npmPackages:
    @vue/test-utils: ^2.2.4 => 2.4.1
    vitest: 0.34.2 => 0.34.2
    vue: ^3.2.1 => 3.3.4

**Comment by cexbrayat** [comment]
That was a tough one to figure out, but I think this is an issue unrelated to VTU.

If you change your vitest config to use the ESM build of the flatpickr library (as the app does when you run `npm run dev`) instead of the UMB build (that Vitest uses), then the issue disappears. Well, it's replaced by a warning about a required props that makes sense):

```
export default mergeConfig(
  viteConfig,
  defineConfig({
    test: {
      environment: 'jsdom',
      exclude: [...configDefaults.exclude, 'e2e/*'],
      root: fileURLToPath(new URL('./', import.meta.url)),
      alias: {
        'vue-flatpickr-component': 'vue-flatpickr-component/dist/esm/index.js'
      }
    }
  })
)
```

I'll close as there is nothing VTU can do about this.

**Comment by dospunk** [comment]
@cexbrayat thank you for your help! I never would have figured that out on my own. I'll let the vue-flatpickr-component devs know!
