### ISSUE TITLE
Bug: Wrapper.Text function is trimming elements

### ISSUE THREAD

**Issue by occitaneUbald** [vuejs/test-utils#2251]
**Describe the bug**
Text function is trimming elements when multiple elements are concatenated

**To Reproduce**
This example works in 2.4.1 but does not work in 2.4.2
```
it('does not work', () => {
    const wrapper = shallowMount({
        template: `<span>Trimmed </span><span>Example</span>`
    })

    expect(wrapper.text()).toBe('Trimmed Example')
})
```

**Expected behavior**
This test should pass as in 2.4.1 version

**Comment by cexbrayat** [comment]
Hi @occitaneUbald 

This is because of this fix in VTU https://github.com/vuejs/test-utils/pull/2231
But I think the new behavior is probably better.

You'll have to update your test to either:
- check with `TrimmedExample`
- check both span elements individually with`element.textContent` if you want to check if the space is there (because `text()` does trim the content).

**Comment by occitaneUbald** [comment]
You should at least mention this in your changelog as it is a breaking change in your API

**Comment by cexbrayat** [comment]
Maybe we should have, but I don't think it was spotted by the contributor who did this fix.

Feel free to open a PR to open the changelog, we'll gladly review it.

**Comment by occitaneUbald** [comment]
And we should probably add an automated test to avoid further undetected regressions in the future on this API
