### ISSUE TITLE
Bug: findComponent doesn't work properly if child component is root of parent component

### ISSUE THREAD

**Issue by ElVisPL** [vuejs/test-utils#2300]
**Describe the bug**
This is known issue in vue test utils v1, but the previous workaround doesn't work anymore

```
<template>
  <WelcomeItem :test="2"> </WelcomeItem>
</template>
```
vs
```
<template>
  <div>
    <WelcomeItem :test="2"> </WelcomeItem>
  </div>
</template>
```

**To Reproduce**

https://stackblitz.com/edit/github-orekbd?file=src%2Fcomponents%2F__tests__%2FTheWelcome.spec.ts

run `yarn test:utils TheWelcome`

**Expected behavior**

`findComponent.props()` returns props of child component

**Related information:**

In vue test utils v1 there was workaround: 
```
const childWrapper = createWrapper(wrapper.vm.$children[0])
```
Now there is no `wrapper.vm.$children`

**Comment by freakzlike** [comment]
Instead of using the tag name `wrapper.findComponent('welcome-item-stub')` you can use the component name `wrapper.findComponent({ name: 'WelcomeItem' })` which correctly returns the props of the component.

I guess the selector does not correctly resolve the component. Therefore the props are not treated correctly and instead returned by `.attributes()`. I will try to investigate the code, when I got some time
