### ISSUE TITLE
Bug: stubbing not working in a Vue+TSX project

### ISSUE THREAD

**Issue by julisch94** [vuejs/test-utils#2438]
Thanks a lot for this amazing library. I've been using it for months!

**Describe the bug**
I want to stub away a Child component that wraps some complex 3rd party logic.
But the Child component doesn't seem to be stubbed. My tests fail and I can see the actual Child component in the debugging output.

**To Reproduce**
A simple and minimal reproduction of the issue:
https://stackblitz.com/edit/vue3-tsx-4glbev?file=src%2FApp.tsx,src%2FChild.tsx,src%2FApp.spec.ts

**Expected behavior**
1) Both unit tests should succeed and 
2) When printing `wrapper.html()` or `screen.debug()` I expect to see something like
```html
<div>
  <h1>App</h1>
  <child-stub></child-stub>
</div>
```

**Related information:**
My minimal reproduction is using the exact library versions as in my own project.
Any help is appreciated!! 😇

**Comment by cexbrayat** [comment]
Hi @julisch94 

Thanks for the repro. I guess this is a problem with JSX (I personally don't use it, and this definitely should work). We don't have a lot of tests with JSX components so maybe this doesn't work.

Would you like to try to open a PR and fix it? A good first step would be to add a unit test to reproduce the issue. Then the issue is probably in https://github.com/vuejs/test-utils/blob/main/src/vnodeTransformers/stubComponentsTransformer.ts.

That would be a great help and we would gladly review and merge it!

**Comment by julisch94** [comment]
I have tried to solve it by adding a failing test case. I was able to fix one of them by defining a `name` inside my component. With that, actually my original bug was solved for me. So no code changes needed.

However, it would be nice if test-utils would be able to determine the component name by itself and just stub it no matter what the `name` of the child component is.

I tried to achieve that in #2441 but couldn't manage to solve the failing test. Maybe you can help?

Anyway, for now I'm happy to just add a `name` to my JSX component and that will fix it for me. So this has no urgency. Thanks for the help anyways. ❤️

**Comment by cexbrayat** [comment]
As discussed in https://github.com/vuejs/test-utils/pull/2441#issuecomment-2134648184 I think adding a name is probably the only way for now, except if the JSX plugin decides to more info to the component 👍
