### ISSUE TITLE
SSR support (render)

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/test-utils#507]
We should support `render`, for SSR: https://vue-test-utils.vuejs.org/api/#render

**Comment by samturrell** [comment]
Migrating from vue 2 to vue 3, and this seems to be a missing feature in the test utils. Is this something that is actively planned to be reintroduced?

**Comment by cexbrayat** [comment]
@samturrell Yes, there is an open PR from a contributor that should land as a first step to support SSR. See https://github.com/vuejs/test-utils/pull/1572

**Comment by lmiller1990** [comment]
@samturrell if you want to pick up where the original author in #1572 left off, that'd be great! I think we just need to rebase and get his branch green, and we can release something to get feedback and testing.

**Comment by craigrileyuk** [comment]
This is a good addition, but I assume it's an emulated function rather than an adapted version of the proper renderToString function since it fails in a NodeJS envrionment. For example:

```// @vitest-environment node```

at the top of your test file gets you a `ReferenceError: document is not defined` from `vue-test-utils.esm-bundler.mjs`.

**Comment by lmiller1990** [comment]
Hm, should `document` be defined in that context? Test Utils assumes `document` exists. 

Any recommendation for how `renderToString` should be implemented here?
